language: node_js
node_js:
  - '10'
env:
  global:
    - APP_ID=EgjCUfNdGw3Tu0TPdKkuG7yy-MdYXbMMI
    - APP_KEY=Gc2YoMOt0kKEYrAL8ECTujbH
    - EXSITING_ROOM_ID=5d0ca75a1da56900089ce410
    - SYS_CONV_ID=5f687464eae7a622625b39ee
install:
  - npm install codecov -g
  - npm install
script:
  - npm test && codecov
  - npm run docs
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
    ./script/deploy.sh;
    ./script/release.sh;
    fi
  - if [[ "$TRAVIS_BRANCH" == "next" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
    ./script/release.sh next-dist;
    fi
  - if [[ "$TRAVIS_BRANCH" == "v5" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
    ./script/release.sh v5-dist;
    fi
